### ISSUE TITLE
Error chaining calls

### ISSUE THREAD

**Issue by frisco82** [node-xbmc/node-xbmc#13]
I am trying to chain calls but everything I try just causes this error:
```
D:\Node\prueba\node_modules\xbmc\node_modules\node-promise\promise.js:204
          throw error;
          ^
```
My current code is (api is a Xbmc.XbmcApi with a stablished connection):
```
      var dfd = api.send('Playlist.Clear', {playlistid: 0});
      dfd.then(function(data) {
        api.send('Playlist.Add', {playlistid: 0, file: file});
```

Indeed the Player.stop method also causes the same error.
The problem is that I also get the same error when calling several sends in a row, so I am not sure how to work around that.

I am using the latest version on a windows machine.

**Comment by moul** [comment]
I don't think this is due to the chaining, I'm more thinking about one of your calls always throwing an error

example: the last issue we encountered was only 11 days ago and was about `Player.stop` always triggering an error: https://github.com/node-xbmc/node-xbmc/issues/12

---

Can you try to get more information about the error, usually you should get a backtrace after the `throw error` line, also, you can try setting up the environment variable `DEBUG=*` which will provides a lot more information so we can more easily debug this

PS: please double-check that your are using version `0.6.0` which is only 8 days old, on this version, you should be able to call `Player.stop` even if you are chaining the calls

**Comment by frisco82** [comment]
Yup that was my fault, that add had some errors in the params
I am pretty new to node and wasn't able to enable that debug, tried catching, enabling verbose on the connection but I couldn't see any extra information.
But I was able to find the error on the playerStop (version 0.6.0 still causes the exception on my setup) so I will comment there.

**Comment by moul** [comment]
ok perfect
